# Generated by Django 3.1.4 on 2020-12-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(max_length=100)),
                ('phone_num', models.CharField(blank='', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('visited', models.BooleanField(default=False)),
                ('phoned', models.BooleanField(default=False)),
                ('phoned_status', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=500)),
                ('legal_person', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'leeta_enterprise_directory',
            },
        ),
    ]
