# Generated by Django 2.1.11 on 2021-01-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'leeta_user',
            },
        ),
        migrations.AddField(
            model_name='enterprisedirectory',
            name='phoned_date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprisedirectory',
            name='legal_person',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enterprisedirectory',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enterprisedirectory',
            name='registrant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='leeta.User'),
            preserve_default=False,
        ),
    ]
