# Generated by Django 2.1.11 on 2020-12-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201229_0342'),
        ('article', '0002_auto_20201201_1713'),
    ]

    operations = [
    ]
